#!/bin/zsh

ensure_dependency() {
  type $1 >/dev/null 2>&1 || {
    echo >&2 "Aborting operation ('$1' is required but not installed)."
    exit 1
  }
}

install_bin_on_cli() {
  ensure_dependency grep

  local DIR="${0:A:h}"
  local LINE="export PATH=\"$DIR/bin:\$PATH\""

  PROFILE=~/.zprofile
  grep -qsFx "$LINE" "$PROFILE" || echo "\n$LINE\n" >>"$PROFILE"

  # ⚠️ Copied / Powerful / Complex
  # exec sudo --login --user "$USER" /bin/sh -c "cd '$PWD'; exec '$SHELL' -l"

  # TODO
  # - 🤔 Create "sh" profile file backup?
  # - Handle using .bash_profile rather than .zprofile
}
